import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import css from "./layout.module.scss";
import { MantineProvider } from "@mantine/core";
import { StoreProvider } from "@artempoletsky/easystore";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/@mantine/core@7.10.1/styles.css" />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <StoreProvider>
            <Header />
            <div className={css.wrapper}>
              {children}
            </div>
            <Footer />
          </StoreProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
